version: '3.5'

services:
  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    image: tin_server:latest
    container_name: app
    ports:
      - "12345:12345"
    volumes:
      # - ./data:/app/data:z,rw
      - .:/app:z,rw
