version: '3.5'

networks:
  tin:
    driver: bridge

services:
  database:
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_PASSWORD: passwd
    networks:
      - tin

  app:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    image: tin_server:latest
    container_name: app
    ports:
      - "12345:12345"
    volumes:
      - ./tin:/app/tin:z,rw
      - ./data:/app/data:z,rw
      - ./conf:/app/conf:z
    networks:
      - tin
    command: ["python", "-m", "tin", "-c", "/app/conf/config.json", "--start"]
  
  sslapp:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    image: tin_server:latest
    container_name: sslapp
    ports:
      - "12346:12345"
    volumes:
      - ./tin:/app/tin:z,rw
      - ./data:/app/data:z,rw
      - ./conf:/app/conf:z
    networks:
      - tin
    command: ["python", "-m", "tin", "-c", "/app/conf/config.json", "--ssl", "--start"]
